# Generated by Django 4.2.7 on 2024-01-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_keyword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='opis',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
