# Generated by Django 4.2.7 on 2024-01-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_instructions_keyword_instrukcja'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='opis_wyniku',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
