# Generated by Django 4.2.7 on 2024-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_keyword_opis_wyniku_alter_keyword_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='opis_wyniku',
            field=models.TextField(default='fsdfsdf'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
