# Generated by Django 4.2.7 on 2023-12-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrukcje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slowo_kluczowe', models.CharField(max_length=255)),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
    ]
