# Generated by Django 4.2.7 on 2024-01-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_keyword_delete_slowokluczowe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
