# Generated by Django 4.2.7 on 2024-01-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_keyword_instrukcja_remove_keyword_opis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='opis_wyniku',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
