# Generated by Django 5.0.1 on 2024-01-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_yourmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourmodel',
            old_name='name',
            new_name='Imie',
        ),
        migrations.RenameField(
            model_name='yourmodel',
            old_name='message',
            new_name='Problem',
        ),
    ]
