# Generated by Django 5.0.1 on 2024-01-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_name_yourmodel_imie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='Fromularz',
        ),
    ]
