# Generated by Django 5.0.1 on 2024-01-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_yourmodel_fromularz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='word',
            new_name='slowo',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='opis_wyniku',
            field=models.TextField(default=''),
        ),
    ]
