# Generated by Django 5.0.1 on 2024-01-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_word_keyword_slowo_alter_keyword_opis_wyniku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='Slowa',
        ),
    ]
