# Generated by Django 5.0.1 on 2024-01-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_keyword_slowa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='timestamp',
            new_name='czas',
        ),
    ]
