# Generated by Django 5.0.1 on 2024-01-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_timestamp_searchhistory_czas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='description',
            new_name='opis',
        ),
    ]
