# Generated by Django 5.0.1 on 2024-01-27 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_instrukcja_searchhistory_sentence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchHistory',
            new_name='Historia',
        ),
    ]
