# Generated by Django 4.2.7 on 2023-12-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slowo_kluczowe', models.CharField(max_length=255)),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='instrukcje',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
