# Generated by Django 4.2.7 on 2024-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historia_alter_instrukcje_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlowoKluczowe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slowo', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Historia',
        ),
        migrations.DeleteModel(
            name='Instrukcje',
        ),
    ]
