# Generated by Django 4.2.7 on 2024-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_keyword_opis_alter_keyword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='opis',
            field=models.TextField(),
        ),
    ]
