# Generated by Django 4.2.7 on 2024-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_keyword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
