# Generated by Django 4.2.7 on 2024-01-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_keyword_opis_wyniku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='instrukcja',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='opis',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='opis_wyniku',
            field=models.TextField(),
        ),
    ]
