# Generated by Django 4.2.7 on 2024-01-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
